// front_end-frameworks/movie-night/src/components/AppFooter.vue
<script setup></script>

<template>
  <footer class="mt-auto w-full border-t border-white/5 bg-slate-950/50">
    <div
      class="mx-auto flex max-w-6xl items-center justify-between px-6 py-8 lg:px-8"
    >
      <span class="text-sm font-extrabold tracking-tight text-white">
        MOVIE NIGHT
      </span>
      <span class="text-sm text-slate-500">
        Trouvez votre prochain film.
      </span>
    </div>
  </footer>
</template>

// front_end-frameworks/movie-night/src/components/AppFooter.jsx
function AppFooter() {
  return (
    <footer className="mt-auto w-full border-t border-white/5 bg-slate-950/50">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-8 lg:px-8">
        <span className="text-sm font-extrabold tracking-tight text-white">
          MOVIE NIGHT
        </span>
        <span className="text-sm text-slate-500">
          Trouvez votre prochain film.
        </span>
      </div>
    </footer>
  );
}

export default AppFooter;
