// front_end-frameworks/mon-catalogue/src/components/MovieCard.jsx
function MovieCard({ movie, onToggleFavorite, onViewDetails }) {
  function handleToggleFavorite(event) {
    event.stopPropagation();
    onToggleFavorite(movie.id);
  }

  function handleViewDetails(event) {
    event.stopPropagation();
    onViewDetails(movie);
  }

  return (
    <article className="group flex flex-col overflow-hidden rounded-2xl border border-white/10 bg-slate-900 transition duration-300 hover:-translate-y-1 hover:border-white/20">
      <div className="relative aspect-[2/3] overflow-hidden bg-slate-800">
        <img
          src={movie.posterImage}
          alt={movie.title}
          loading="lazy"
          className="h-full w-full object-cover transition duration-300 group-hover:scale-105"
        />

        <span className="absolute left-3 top-3 rounded-lg bg-slate-950/80 px-2.5 py-1 text-xs font-bold text-amber-400 backdrop-blur">
          &#9733; {movie.personalRating}
        </span>

        <button
          type="button"
          onClick={handleToggleFavorite}
          aria-pressed={movie.favorite}
          aria-label={
            movie.favorite ? "Retirer des favoris" : "Ajouter aux favoris"
          }
          className={`absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-slate-950/80 text-lg backdrop-blur transition hover:bg-slate-950 ${
            movie.favorite ? "text-rose-500" : "text-slate-400"
          }`}
        >
          &#9829;
        </button>
      </div>

      <div className="flex flex-1 flex-col gap-3 p-5">
        <h2 className="text-lg font-bold leading-tight text-white">
          {movie.title}
        </h2>

        <div className="flex items-center gap-2 text-sm text-slate-400">
          <span>{movie.year}</span>
          <span className="text-slate-600">&bull;</span>
          <span className="rounded-md border border-white/10 bg-white/5 px-2 py-0.5 text-xs font-semibold text-slate-300">
            {movie.category}
          </span>
        </div>

        <button
          type="button"
          onClick={handleViewDetails}
          className="mt-auto rounded-xl bg-gradient-to-br from-rose-500 to-pink-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:opacity-90"
        >
          Voir le détail
        </button>
      </div>
    </article>
  );
}

export default MovieCard;

// front_end-frameworks/movie-night/src/components/MovieCard.vue
<script setup>
defineProps({
  movie: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <div
    class="group overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-lg transition duration-300 hover:-translate-y-1 hover:border-slate-700"
  >
    <button
      type="button"
      class="absolute right-3 top-3 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-black/60 text-white backdrop-blur transition-colors hover:bg-red-600 hover:text-white"
      aria-label="Ajouter aux favoris"
    >
      <span>♡</span>
    </button>
    <div class="rounded-xl bg-slate-900 p-4">
      <div class="relative overflow-hidden">
        <img :src="movie.image" :alt="movie.title" class="aspect-2/3 w-full object-cover transition duration-300 group-hover:scale-105" />
      </div>
      <h3 class="mt-2 font-bold text-white">{{ movie.title }}</h3>
      <p class="text-sm text-slate-400">
        ★ {{ movie.rating }} · {{ movie.year }}
      </p>
      <p class="text-xs text-slate-500">{{ movie.category }}</p>
    </div>
    <button
    type="button"
    class="mt-3 w-full rounded-lg bg-white/10 px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-white/20 focus:outline-none focus:ring-2 focus:ring-white/40"
    
    >
        Voir le détail
    </button>
  </div>
</template>
