// front_end-frameworks/vue/src/components/ui/Button.vue
<script setup>
defineProps({
  href: {
    type: String,
    default: null,
  },
  variant: {
    type: String,
    default: "primary",
  },
});

const baseClasses =
  "inline-flex items-center justify-center gap-2 rounded-md px-4 py-2 font-semibold text-white transition-colors";
</script>

<template>
  <a
    v-if="href"
    :href="href"
    :class="[
      baseClasses,
      variant === 'primary'
        ? 'bg-violet-600 shadow-lg shadow-violet-600/40 hover:bg-violet-700'
        : 'border border-slate-800 bg-slate-950 hover:bg-slate-900',
    ]"
  >
    <slot />
  </a>
  <button
    v-else
    :class="[
      baseClasses,
      variant === 'primary'
        ? 'bg-violet-600 shadow-lg shadow-violet-600/40 hover:bg-violet-700'
        : 'border border-slate-800 bg-slate-950 hover:bg-slate-900',
    ]"
  >
    <slot />
  </button>
</template>

// front_end-frameworks/react/src/components/ui/Button.jsx
function Button({
  href,
  variant = "primary",
  className = "",
  children,
  ...rest
}) {
  const baseClasses =
    "inline-flex items-center justify-center gap-2 rounded-md px-4 py-2 font-semibold text-white transition-colors";
  const variantClasses =
    variant === "primary"
      ? "bg-violet-600 shadow-lg shadow-violet-600/40 hover:bg-violet-700"
      : "border border-slate-800 bg-slate-950 hover:bg-slate-900";

  const classes = `${baseClasses} ${variantClasses} ${className}`;

  if (href) {
    return (
      <a href={href} className={classes} {...rest}>
        {children}
      </a>
    );
  }

  return (
    <button className={classes} {...rest}>
      {children}
    </button>
  );
}

export default Button;
