// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from "./components/layout/Header.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import About from "./sections/About.svelte";
  import Features from "./sections/Features.svelte";
  import Insights from "./sections/Insights.svelte";
  import Contact from "./sections/Contact.svelte";
  import Footer from "./components/layout/Footer.svelte";
</script>

<div class="bg-black">
  <Header />
  <main>
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
  </main>
  <Footer />
</div>

// front_end-frameworks/react/src/App.jsx
import Header from "./components/layout/Header";
import Hero from "./components/sections/Hero";
import About from "./sections/About";
import Features from "./sections/Features";
import Insights from "./sections/Insights";
import Contact from "./sections/Contact";
import Footer from "./components/layout/Footer";

function App() {
  return (
    <div className="bg-black">
      <Header />
      <main>
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}

export default App;
