// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from "./components/layout/Header.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import About from "./sections/About.svelte";
  import Features from "./sections/Features.svelte";
  import Insights from "./sections/Insights.svelte";
  import Contact from "./sections/Contact.svelte";
  import Footer from "./components/layout/Footer.svelte";
</script>

<div class="bg-black">
  <Header />
  <main>
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
  </main>
  <Footer />
</div>

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from "./components/layout/Header.vue";
import Hero from "./components/sections/Hero.vue";
import About from "./sections/About.vue";
import Features from "./sections/Features.vue";
import Insights from "./sections/Insights.vue";
import Contact from "./sections/Contact.vue";
import Footer from "./components/layout/Footer.vue";
</script>

<template>
  <div class="bg-black">
    <Header />
    <main>
      <Hero />
      <About />
      <Features />
      <Insights />
      <Contact />
    </main>
    <Footer />
  </div>
</template>
