// front_end-frameworks/react/src/components/ui/SectionTitle.jsx
function SectionTitle({ line1, line2, variant = "section", accent }) {
  const isHero = variant === "hero";
  const Tag = isHero ? "h1" : "h2";
  const accentClass = accent ?? (isHero ? "text-violet-300" : "text-violet-400");

  return (
    <Tag
      className={`mt-6 leading-none font-black tracking-tight text-white ${
        isHero ? "text-5xl md:text-7xl" : "text-4xl md:text-5xl"
      }`}
    >
      {line1}
      <br />
      <span className={accentClass}>{line2}</span>
    </Tag>
  );
}

export default SectionTitle;

// front_end-frameworks/svelte/src/components/ui/SectionTitle.svelte
<script>
  let { line1, line2, variant = "section", accent } = $props();

  const isHero = $derived(variant === "hero");
  const Tag = $derived(isHero ? "h1" : "h2");
  const accentClass = $derived(
    accent ?? (isHero ? "text-violet-300" : "text-violet-400"),
  );
</script>

<svelte:element
  this={Tag}
  class={`mt-6 leading-none font-black tracking-tight text-white ${
    isHero ? "text-5xl md:text-7xl" : "text-4xl md:text-5xl"
  }`}
>
  {line1}
  <br />
  <span class={accentClass}>{line2}</span>
</svelte:element>
